### ISSUE TITLE
Type 2 Upcs

### ISSUE THREAD

**Issue by robjewell-ibotta** [wankdanker/gs1#4]
Hello, does this package include validation and check digit generation for [type 2 upcs](https://www.retailedge.com/help/random_weight_type_2_upc_items.htm)?

**Comment by wankdanker** [comment]
Hi @robjewell-ibotta the package does not have any specific handling for type 2 upcs. But, based on the link you provided, it seems like it would still work. If you create a value like 21234501224 where 12345 is the SKU and 1224 is the price (12.24) then it would generate a check digit for that and give you the complete 12 digit UPC.

Is there any specific validation you were looking for?

**Comment by robjewell-ibotta** [comment]
@wankdanker thank you very much for your reply.

When I try this UPC `212345019954` from the docs under UPC Example, the output I get from `gs1` is an added check digit `9` and `false` on validate:
```
=== upc ===
212345019954
=== upc ===
=== gs1 ===
2123450199549
false
2123450199549
=== gs1 ===
```

Assuming the docs provide a valid UPC, I expect `gs1` not to add a check digit and return `true` on validate. Am I missing something?


Here is [an example](https://github.com/robjewell-ibotta/type-2/blob/main/index.js).

**Comment by wankdanker** [comment]
Hi @robjewell-ibotta!

The `gs1` function always calculates and appends a check digit (it's not a constructor function). The call to `gs1.validate('212345019954')` is returning false because 4 is not the correct check digit for `21234501995` (the correct check digit is 5). The call to `gs1.checkdigit('212345019954')` is calculating a check digit on `212345019954`.

Not sure if this helps clear things up, or maybe I'm misunderstanding something. Let me know!

**Comment by robjewell-ibotta** [comment]
ok I think I understand -- the UPC provided in [the docs](https://www.retailedge.com/help/random_weight_type_2_upc_items.htm) (`212345019954`; screenshot below) has an incorrect check digit `4`.
![Screen Shot 2022-02-03 at 12 28 40 PM](https://user-images.githubusercontent.com/85700100/152396239-d39ffdda-a007-4238-8c4f-26dd4595e0c9.png)

In short the UPC, `212345019954`, is invalid
